package com.usefulapps.factchecker.ui.theme
import androidx.compose.ui.graphics.Color

// Terracotta Earth palette from Stitch designs
val primaryLight = Color(0xFF781F00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9A3412)
val onPrimaryContainerLight = Color(0xFFFFBDA9)
val secondaryLight = Color(0xFF884F3E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFB59F)
val onSecondaryContainerLight = Color(0xFF7A4433)
val tertiaryLight = Color(0xFF004172)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF005999)
val onTertiaryContainerLight = Color(0xFFABCFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFCF9F4)
val onBackgroundLight = Color(0xFF1C1C19)
val surfaceLight = Color(0xFFFCF9F4)
val onSurfaceLight = Color(0xFF1C1C19)
val surfaceVariantLight = Color(0xFFE5E2DD)
val onSurfaceVariantLight = Color(0xFF57423C)
val outlineLight = Color(0xFF8B716A)
val outlineVariantLight = Color(0xFFDEC0B7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF31302D)
val inverseOnSurfaceLight = Color(0xFFF3F0EB)
val inversePrimaryLight = Color(0xFFFFB59F)
val surfaceDimLight = Color(0xFFDCDAD5)
val surfaceBrightLight = Color(0xFFFCF9F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3EE)
val surfaceContainerLight = Color(0xFFF0EDE9)
val surfaceContainerHighLight = Color(0xFFEBE8E3)
val surfaceContainerHighestLight = Color(0xFFE5E2DD)

// Dark terracotta
val primaryDark = Color(0xFFFFB59F)
val onPrimaryDark = Color(0xFF3A0A00)
val primaryContainerDark = Color(0xFF9A3412)
val onPrimaryContainerDark = Color(0xFFFFBDA9)
val secondaryDark = Color(0xFFFFB59F)
val onSecondaryDark = Color(0xFF360F04)
val secondaryContainerDark = Color(0xFF6C3929)
val onSecondaryContainerDark = Color(0xFFFFDbd1)
val tertiaryDark = Color(0xFFA0CAFF)
val onTertiaryDark = Color(0xFF001C37)
val tertiaryContainerDark = Color(0xFF005999)
val onTertiaryContainerDark = Color(0xFFABCFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1C1C19)
val onBackgroundDark = Color(0xFFE5E2DD)
val surfaceDark = Color(0xFF1C1C19)
val onSurfaceDark = Color(0xFFE5E2DD)
val surfaceVariantDark = Color(0xFF49454E)
val onSurfaceVariantDark = Color(0xFFDEC0B7)
val outlineDark = Color(0xFF958E99)
val outlineVariantDark = Color(0xFF49454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2DD)
val inverseOnSurfaceDark = Color(0xFF31302D)
val inversePrimaryDark = Color(0xFF781F00)
val surfaceDimDark = Color(0xFF1C1C19)
val surfaceBrightDark = Color(0xFF3B383E)
val surfaceContainerLowestDark = Color(0xFF0F0D12)
val surfaceContainerLowDark = Color(0xFF1D1A20)
val surfaceContainerDark = Color(0xFF211E24)
val surfaceContainerHighDark = Color(0xFF2C292F)
val surfaceContainerHighestDark = Color(0xFF37333A)

// Semantic colors for verdict badges
val VerdictTrue = Color(0xFF10B981)        // emerald
val VerdictMisleading = Color(0xFFF59E0B)  // amber
val VerdictFalse = Color(0xFFEF4444)       // red
val VerdictDisputed = Color(0xFF8B5CF6)    // violet
val VerdictUnverifiable = Color(0xFF6B7280) // gray